// Builds src/tokens/tokens.json (W3C DTCG) and src/tokens/tokens.css
// from the raw Figma Variables export in figma-variables.json.
// Run: npm run tokens
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '../../src/tokens');
const raw = JSON.parse(readFileSync(join(here, 'figma-variables.json'), 'utf8'));

const col = Object.fromEntries(raw.columns.map((c, i) => [c, i]));
const rows = raw.variables.map((r) => ({
  path: r[col.name].split('/'),
  type: r[col.type] === 'C' ? 'color' : 'dimension',
  light: r[col.Light],
  dark: r[col.Dark],
  description: r[col.description],
}));

// DTCG forbids a node being both a token and a group (e.g. `button/primary/text`
// and `button/primary/text/disabled`). Such tokens move to `<path>/default`.
const key = (p) => p.join('/');
const renames = new Map();
for (const row of rows) {
  const k = key(row.path);
  if (rows.some((o) => key(o.path).startsWith(k + '/'))) {
    renames.set(k, [...row.path, 'default']);
    row.path = [...row.path, 'default'];
  }
}
const resolvePath = (figmaName) => renames.get(figmaName) ?? figmaName.split('/');

const isAlias = (v) => typeof v === 'string' && v.startsWith('{');
const aliasPath = (v) => resolvePath(v.slice(1, -1));

// ---------- DTCG JSON ----------
const hexToColor = (hex) => {
  const n = hex.slice(1);
  const ch = (i) => parseInt(n.slice(i, i + 2), 16) / 255;
  const round = (x) => Math.round(x * 10000) / 10000;
  const color = { colorSpace: 'srgb', components: [0, 2, 4].map((i) => round(ch(i))) };
  if (n.length === 8) color.alpha = round(ch(6));
  color.hex = '#' + n.slice(0, 6);
  return color;
};

const toDtcgValue = (v, type) => {
  if (isAlias(v)) return `{${aliasPath(v).join('.')}}`;
  return type === 'color' ? hexToColor(v) : { value: v, unit: 'px' };
};

const tierDescriptions = {
  primitives: 'Raw palette and scales. Never use directly in components.',
  semantic: 'Intent-based tokens. $value is the Light mode; $extensions.mode holds light/dark.',
  component: 'Component-scoped tokens. Alias semantic tokens only.',
};

const tree = {
  $description: `Generated from Figma collection "${raw.collection}" (${raw.source}). Do not edit by hand.`,
};
for (const row of rows) {
  let node = tree;
  for (const seg of row.path.slice(0, -1)) {
    node[seg] ??= tierDescriptions[seg] ? { $description: tierDescriptions[seg] } : {};
    node = node[seg];
  }
  const token = { $type: row.type, $value: toDtcgValue(row.light, row.type) };
  if (row.description) token.$description = row.description;
  if (row.path[0] === 'semantic') {
    token.$extensions = {
      mode: { light: toDtcgValue(row.light, row.type), dark: toDtcgValue(row.dark, row.type) },
    };
  }
  node[row.path.at(-1)] = token;
}

// ---------- CSS ----------
const cssVar = (p) => `--${p.join('-')}`;
const toCssValue = (v, type) => {
  if (isAlias(v)) return `var(${cssVar(aliasPath(v))})`;
  return type === 'color' ? v : `${v}px`;
};
const decls = (list, mode) =>
  list.map((r) => `  ${cssVar(r.path)}: ${toCssValue(r[mode], r.type)};`).join('\n');

const tier = (name) => rows.filter((r) => r.path[0] === name);
const primitives = tier('primitives');
const semantic = tier('semantic');
const component = tier('component');

const css = `/**
 * Design tokens — generated by scripts/tokens/build.mjs from Figma "${raw.collection}".
 * Do not edit by hand; run \`npm run tokens\`.
 *
 * Theming: Light is the default. Dark applies via [data-theme="dark"]
 * or the OS preference (unless [data-theme="light"] is set).
 */

/* 1. Primitives */
:root {
${decls(primitives, 'light')}
}

/* 2. Semantic — Light */
:root,
[data-theme='light'] {
  color-scheme: light;
${decls(semantic, 'light')}
}

/* 2. Semantic — Dark */
[data-theme='dark'] {
  color-scheme: dark;
${decls(semantic, 'dark')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${decls(semantic, 'dark').replace(/^/gm, '  ')}
  }
}

/* 3. Component — re-declared on every themed subtree so nested themes resolve correctly */
:root,
[data-theme] {
${decls(component, 'light')}
}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'tokens.json'), JSON.stringify(tree, null, 2) + '\n');
writeFileSync(join(outDir, 'tokens.css'), css);

console.log(
  `tokens: ${primitives.length} primitives, ${semantic.length} semantic, ${component.length} component`,
);
for (const [from, to] of renames) console.warn(`renamed ${from} -> ${to.join('/')} (token/group name clash)`);
